In [1]:
import numpy as np

In [1]:
a = [10,11,12,13,14,15]

In [2]:
import numpy as np

In [3]:
n_a = np.array(a)

In [4]:
n_a

array([10, 11, 12, 13, 14, 15])

In [8]:
n_a[0]

10

In [9]:
n_a[1]

11

In [17]:
last_index = len(n_a) -1

In [18]:
n_a[last_index]

15

In [13]:
n_a[-1]

15

In [14]:
n_a[-2]

14

In [37]:
n_a[1:-1]

array([11, 12, 13, 14])

In [38]:
mean_value = np.mean(n_a)
mean_value

12.5

In [43]:
n_random = np.random.random(10) 
n_random


0.04481103044351775

In [41]:
np.max(n_random) 


0.7255385684463684

In [42]:
np.min(n_random) 

0.10111359447407464

In [45]:
np.sort(n_random)

array([0.04481103, 0.1075077 , 0.24535152, 0.52350928, 0.53300365,
       0.73849866, 0.79906098, 0.81275738, 0.8848958 , 0.94060196])

In [46]:
np.argsort(n_random)

array([0, 4, 3, 8, 1, 7, 9, 2, 5, 6])

In [48]:
np.sort(n_random)[::-1]

array([0.94060196, 0.8848958 , 0.81275738, 0.79906098, 0.73849866,
       0.53300365, 0.52350928, 0.24535152, 0.1075077 , 0.04481103])